title: My custom title TODO
description: maybe i could put some description here

show_downloads: "false"

navbar-links:
  About Me: "aboutme"

markdown: kramdown

kramdown:
   input: GFM

#link-tags: true

#plugins:
#  - jekyll-sitemap
#  - jekyll-paginate

theme: minima
#github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# theme: jekyll-theme-primer
# gfm_quirks: paragraph_end
